### ISSUE TITLE
clarification on /req/ogc-process-description/input-mixed-type

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-ogcapi-processes10#69] opened 2023-07-03 18:14 UTC
As part of pygeoapi testing for OGC API - Processes CITE Compliance, I am getting the following error against `/req/ogc-process-description/input-mixed-type`

`No Input definition of 'hello-world' process identifies a Mixed Type input`

Any idea? The process is defined at https://demo.pygeoapi.io/master/processes/hello-world?f=json

Note I am running both pygeoapi and ets-ogcapi-processes10 locally via Docker, with some local changes to pygeoapi, which I doubt are related to this issue.  I'm also not sure whether an official `echo` process is supposed to be specifically implemented for consistency.

cc @ghobona @jerstlouis @gfenoy 

Screenshot below:

![image](https://github.com/opengeospatial/ets-ogcapi-processes10/assets/910430/aa1ebeb1-ee87-44c6-b345-0cc366e7ce3f)

**Comment by bpross-52n** [comment] 2023-07-27 12:22
Duplicate of #53. We will close this one. Please refer to #53.

**Closed by bpross-52n** 2023-07-27 12:22 UTC
Labels: bug, duplicate
